# Step 1: Build the Angular application
FROM node:18 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Build the Angular application
RUN npm run build --prod

# Step 2: Serve the application
FROM nginx:alpine

# Copy the built Angular application from the previous stage
COPY --from=build /app/dist/crud-front-end /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Configure Nginx to serve the Angular application
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
